//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSON_WCF_Client.SOAPAndJSONService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPAndJSONService.ISOAPAndJSONService")]
    public interface ISOAPAndJSONService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPAndJSONService/DoStuff", ReplyAction="http://tempuri.org/ISOAPAndJSONService/DoStuffResponse")]
        JSON_WCF_Model.Output DoStuff(JSON_WCF_Model.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPAndJSONService/DoStuff", ReplyAction="http://tempuri.org/ISOAPAndJSONService/DoStuffResponse")]
        System.Threading.Tasks.Task<JSON_WCF_Model.Output> DoStuffAsync(JSON_WCF_Model.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPAndJSONService/DoOtherStuff", ReplyAction="http://tempuri.org/ISOAPAndJSONService/DoOtherStuffResponse")]
        JSON_WCF_Model.Output DoOtherStuff(JSON_WCF_Model.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPAndJSONService/DoOtherStuff", ReplyAction="http://tempuri.org/ISOAPAndJSONService/DoOtherStuffResponse")]
        System.Threading.Tasks.Task<JSON_WCF_Model.Output> DoOtherStuffAsync(JSON_WCF_Model.Input input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISOAPAndJSONServiceChannel : JSON_WCF_Client.SOAPAndJSONService.ISOAPAndJSONService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOAPAndJSONServiceClient : System.ServiceModel.ClientBase<JSON_WCF_Client.SOAPAndJSONService.ISOAPAndJSONService>, JSON_WCF_Client.SOAPAndJSONService.ISOAPAndJSONService {
        
        public SOAPAndJSONServiceClient() {
        }
        
        public SOAPAndJSONServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SOAPAndJSONServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPAndJSONServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPAndJSONServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JSON_WCF_Model.Output DoStuff(JSON_WCF_Model.Input input) {
            return base.Channel.DoStuff(input);
        }
        
        public System.Threading.Tasks.Task<JSON_WCF_Model.Output> DoStuffAsync(JSON_WCF_Model.Input input) {
            return base.Channel.DoStuffAsync(input);
        }
        
        public JSON_WCF_Model.Output DoOtherStuff(JSON_WCF_Model.Input input) {
            return base.Channel.DoOtherStuff(input);
        }
        
        public System.Threading.Tasks.Task<JSON_WCF_Model.Output> DoOtherStuffAsync(JSON_WCF_Model.Input input) {
            return base.Channel.DoOtherStuffAsync(input);
        }
    }
}
